import type { ChecklistTaskTemplate } from "../types";

// Conteúdo inicial de exemplo, focado em organização/planejamento/preparação/
// compras/documentação — nunca em orientação médica individualizada.
export const CHECKLIST_TASKS: ChecklistTaskTemplate[] = [
  // Primeiro trimestre (semanas 1-13)
  {
    id: "t01",
    title: "Escolher o profissional de saúde que vai te acompanhar",
    description: "Defina com quem você fará o pré-natal e agende a primeira consulta.",
    category: "organizacao",
    startWeek: 1,
    endWeek: 8,
    priority: "alta",
  },
  {
    id: "t02",
    title: "Reunir seus documentos pessoais",
    description: "Separe RG, CPF, comprovante de residência e carteirinha do convênio, se tiver.",
    category: "documentos",
    startWeek: 1,
    endWeek: 12,
    priority: "media",
  },
  {
    id: "t03",
    title: "Contar a novidade e organizar sua rotina",
    description: "Planeje como ajustar trabalho e compromissos nos próximos meses.",
    category: "organizacao",
    startWeek: 4,
    endWeek: 12,
    priority: "media",
  },
  {
    id: "t04",
    title: "Pesquisar sobre licença-maternidade",
    description: "Entenda prazos e documentos necessários no seu país/empresa.",
    category: "documentos",
    startWeek: 8,
    endWeek: 20,
    priority: "media",
  },
  {
    id: "t05",
    title: "Começar a pensar no orçamento do bebê",
    description: "Tenha uma ideia inicial de quanto você pretende investir na preparação.",
    category: "financeiro",
    startWeek: 10,
    endWeek: 16,
    priority: "media",
  },

  // Segundo trimestre (semanas 14-27)
  {
    id: "t06",
    title: "Revisar a lista do enxoval",
    description: "Dê uma primeira olhada nas categorias de itens que vai precisar.",
    category: "enxoval",
    startWeek: 14,
    endWeek: 20,
    priority: "alta",
  },
  {
    id: "t07",
    title: "Pesquisar os principais itens necessários",
    description: "Compare tipos de berço, carrinho e itens de maior investimento.",
    category: "enxoval",
    startWeek: 14,
    endWeek: 24,
    priority: "media",
  },
  {
    id: "t08",
    title: "Conversar sobre o orçamento do enxoval",
    description: "Alinhe com quem for te ajudar o quanto pretendem gastar por categoria.",
    category: "financeiro",
    startWeek: 15,
    endWeek: 22,
    priority: "media",
  },
  {
    id: "t09",
    title: "Definir onde o bebê vai dormir",
    description: "Escolha o cômodo/espaço e comece a planejar a organização do quarto.",
    category: "casa",
    startWeek: 16,
    endWeek: 24,
    priority: "media",
  },
  {
    id: "t10",
    title: "Pesquisar maternidades ou hospitais",
    description: "Levante opções e informações práticas (documentos, visitas, convênio).",
    category: "organizacao",
    startWeek: 18,
    endWeek: 28,
    priority: "media",
  },
  {
    id: "t11",
    title: "Fazer o chá de bebê (se for o caso)",
    description: "Planeje data, lista de convidados e lista de presentes com antecedência.",
    category: "organizacao",
    startWeek: 20,
    endWeek: 30,
    priority: "baixa",
  },
  {
    id: "t12",
    title: "Iniciar as compras do enxoval básico",
    description: "Comece pelos itens de maior prioridade: roupas de recém-nascido e itens de higiene.",
    category: "enxoval",
    startWeek: 20,
    endWeek: 28,
    priority: "alta",
  },

  // Terceiro trimestre (semanas 28-36)
  {
    id: "t13",
    title: "Montar o quarto do bebê",
    description: "Organize móveis, decoração e o espaço de troca de fraldas.",
    category: "casa",
    startWeek: 28,
    endWeek: 34,
    priority: "alta",
  },
  {
    id: "t14",
    title: "Pesquisar cadeirinha para o carro",
    description: "Verifique a exigência legal do seu país e compare modelos.",
    category: "enxoval",
    startWeek: 28,
    endWeek: 34,
    priority: "alta",
  },
  {
    id: "t15",
    title: "Organizar os documentos para a maternidade",
    description: "Separe uma pasta com documentos, exames e cartão do convênio.",
    category: "documentos",
    startWeek: 30,
    endWeek: 37,
    priority: "media",
  },
  {
    id: "t16",
    title: "Planejar quem vai te ajudar nas primeiras semanas",
    description: "Combine com família/rede de apoio a rotina do pós-parto.",
    category: "organizacao",
    startWeek: 30,
    endWeek: 37,
    priority: "media",
  },
  {
    id: "t17",
    title: "Revisar o progresso do enxoval",
    description: "Confira o que já foi comprado e o que ainda falta adquirir.",
    category: "enxoval",
    startWeek: 32,
    endWeek: 37,
    priority: "media",
  },
  {
    id: "t18",
    title: "Registrar o bebê na maternidade e no plano de saúde",
    description: "Levante com antecedência os documentos exigidos para isso.",
    category: "documentos",
    startWeek: 32,
    endWeek: 40,
    priority: "baixa",
  },

  // Preparação final (semanas 37-42)
  {
    id: "t19",
    title: "Montar a mala da maternidade",
    description: "Separe itens para você, acompanhante e bebê com antecedência.",
    category: "maternidade",
    startWeek: 34,
    endWeek: 39,
    priority: "alta",
  },
  {
    id: "t20",
    title: "Deixar a cadeirinha instalada no carro",
    description: "Garanta que o item esteja pronto antes da data prevista.",
    category: "enxoval",
    startWeek: 36,
    endWeek: 39,
    priority: "alta",
  },
  {
    id: "t21",
    title: "Definir a rota até a maternidade",
    description: "Combine transporte e um plano B com quem for te acompanhar.",
    category: "organizacao",
    startWeek: 36,
    endWeek: 40,
    priority: "media",
  },
  {
    id: "t22",
    title: "Conferir o checklist final",
    description: "Revise tudo o que precisa estar pronto antes da chegada do bebê.",
    category: "maternidade",
    startWeek: 38,
    endWeek: 42,
    priority: "alta",
  },
  {
    id: "t23",
    title: "Deixar a casa organizada para o pós-parto",
    description: "Adiante tarefas domésticas e refeições para as primeiras semanas.",
    category: "casa",
    startWeek: 36,
    endWeek: 41,
    priority: "media",
  },
];
