import type { ProductRecommendation } from "../types";

// IMPORTANTE: estes são dados fictícios de demonstração (isPlaceholder: true,
// storeName "Loja Exemplo", URLs em exemplo.com). Nenhum link de afiliado
// real deve ser usado sem configuração manual — substitua regularProductUrl/
// affiliateUrl por parceiros reais antes de produção.
export const PRODUCT_RECOMMENDATIONS: ProductRecommendation[] = [
  {
    id: "p01",
    layetteItemId: "l01",
    productName: "Kit body manga curta (exemplo)",
    productDescription: "Kit com 5 bodies de algodão, tamanho RN — exemplo de produto.",
    productImageUrl: null,
    category: "roupas",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/kit-body-manga-curta",
    affiliateUrl: null,
    currency: "BRL",
    price: 129.9,
    priority: "media",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p07",
    layetteItemId: "l01",
    productName: "Body de bebê (exemplo)",
    productDescription: "Body unitário 100% algodão — exemplo de produto (opção alternativa).",
    productImageUrl: null,
    category: "roupas",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/body-bebe",
    affiliateUrl: null,
    currency: "BRL",
    price: 79.9,
    priority: "baixa",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p02",
    layetteItemId: "l14",
    productName: "Berço padrão americano (exemplo)",
    productDescription: "Berço em MDF com grades reguláveis — exemplo de produto.",
    productImageUrl: null,
    category: "quarto",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/berco-padrao-americano",
    affiliateUrl: null,
    currency: "BRL",
    price: 1450,
    priority: "alta",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p03",
    layetteItemId: "l22",
    productName: "Bebê conforto grupo 0+ (exemplo)",
    productDescription: "Cadeirinha para recém-nascidos, compatível com a maioria dos carros — exemplo.",
    productImageUrl: null,
    category: "passeios",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/bebe-conforto",
    affiliateUrl: null,
    currency: "BRL",
    price: 799.9,
    priority: "alta",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p03us",
    layetteItemId: "l22",
    productName: "Infant car seat (example)",
    productDescription: "Rear-facing infant car seat, group 0+ — example product.",
    productImageUrl: null,
    category: "passeios",
    countryCode: "US",
    storeName: "Example Store",
    storeLogoUrl: null,
    regularProductUrl: "https://www.example.com/products/infant-car-seat",
    affiliateUrl: null,
    currency: "USD",
    price: 129.99,
    priority: "alta",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p04",
    layetteItemId: "l08",
    productName: "Banheira com apoio anatômico (exemplo)",
    productDescription: "Banheira com apoio para recém-nascidos — exemplo de produto.",
    productImageUrl: null,
    category: "banho_higiene",
    countryCode: "*",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/banheira-anatomica",
    affiliateUrl: null,
    currency: "BRL",
    price: 179.9,
    priority: "media",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p05",
    layetteItemId: "l23",
    productName: "Carrinho de bebê (exemplo)",
    productDescription: "Carrinho dobrável, leve para o dia a dia — exemplo de produto.",
    productImageUrl: null,
    category: "passeios",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/carrinho-leve",
    affiliateUrl: null,
    currency: "BRL",
    price: 1299.0,
    priority: "media",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p05b",
    layetteItemId: "l23",
    productName: "Carrinho de passeio compacto (exemplo)",
    productDescription: "Modelo compacto, ideal para viagens — exemplo de produto (opção alternativa).",
    productImageUrl: null,
    category: "passeios",
    countryCode: "BR",
    storeName: "Loja Exemplo 2",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/carrinho-compacto",
    affiliateUrl: null,
    currency: "BRL",
    price: 1899.0,
    priority: "baixa",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p06",
    layetteItemId: "l19",
    productName: "Kit mamadeiras anticólica (exemplo)",
    productDescription: "Kit com 3 mamadeiras de tamanhos variados — exemplo de produto.",
    productImageUrl: null,
    category: "alimentacao",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/kit-mamadeiras",
    affiliateUrl: null,
    currency: "BRL",
    price: 149.9,
    priority: "baixa",
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: "p08",
    layetteItemId: null,
    productName: "Travesseiro para gestante (exemplo)",
    productDescription: "Travesseiro de corpo inteiro para apoio durante a gestação — exemplo de produto.",
    productImageUrl: null,
    category: "geral",
    countryCode: "BR",
    storeName: "Loja Exemplo",
    storeLogoUrl: null,
    regularProductUrl: "https://www.exemplo.com/produtos/travesseiro-gestante",
    affiliateUrl: null,
    currency: "BRL",
    price: 199.9,
    priority: "baixa",
    isActive: true,
    isPlaceholder: true,
  },
];
